name: sw

on:
  push:
  pull_request:
  schedule:
    # every day
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master

    - name: build
      run: ./sw -static build

    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: .sw/out/**/*.exe
